/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.miniproyecto_2;

/**
 *
 * @author julda
 */
public class VentanaResultados extends javax.swing.JFrame {

    /**
     * Creates new form VentanaResultados
     */
    public VentanaResultados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTerminar = new javax.swing.JLabel();
        lCantAciertos = new javax.swing.JLabel();
        lCantFallos = new javax.swing.JLabel();
        lPuntajeTotal = new javax.swing.JLabel();
        lTiempoJugado = new javax.swing.JLabel();
        lAciertos = new javax.swing.JLabel();
        lFallos = new javax.swing.JLabel();
        lPuntaje = new javax.swing.JLabel();
        lTiempo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lTerminar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lTerminar.setText("JUEGO TERMINADO");

        lCantAciertos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lCantAciertos.setText("CANTIDAD DE ACIERTOS:");

        lCantFallos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lCantFallos.setText("CANTIDAD DE FALLOS:");

        lPuntajeTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lPuntajeTotal.setText("PUNTAJE TOTAL:");

        lTiempoJugado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lTiempoJugado.setText("TIEMPO JUGADO:");

        lAciertos.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lAciertos.setText("\"ACIERTOS\"");

        lFallos.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lFallos.setText("\"FALLOS\"");

        lPuntaje.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lPuntaje.setText("\"PUNTAJE\"");

        lTiempo.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lTiempo.setText("\"TIEMPO\"");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(lTerminar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lCantAciertos)
                            .addComponent(lCantFallos)
                            .addComponent(lPuntajeTotal)
                            .addComponent(lTiempoJugado))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lTiempo)
                            .addComponent(lPuntaje)
                            .addComponent(lFallos)
                            .addComponent(lAciertos))))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTerminar)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCantAciertos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lAciertos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lCantFallos)
                    .addComponent(lFallos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lPuntajeTotal)
                    .addComponent(lPuntaje))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTiempoJugado)
                    .addComponent(lTiempo))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lAciertos;
    private javax.swing.JLabel lCantAciertos;
    private javax.swing.JLabel lCantFallos;
    private javax.swing.JLabel lFallos;
    private javax.swing.JLabel lPuntaje;
    private javax.swing.JLabel lPuntajeTotal;
    private javax.swing.JLabel lTerminar;
    private javax.swing.JLabel lTiempo;
    private javax.swing.JLabel lTiempoJugado;
    // End of variables declaration//GEN-END:variables
}
